// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/korovindenis/shutdown-from-browser/v2/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// IComputerUsecase is an autogenerated mock type for the IComputerUsecase type
type IComputerUsecase struct {
	mock.Mock
}

// GetModePowerOff provides a mock function with given fields:
func (_m *IComputerUsecase) GetModePowerOff() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTimePowerOff provides a mock function with given fields:
func (_m *IComputerUsecase) GetTimePowerOff() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsNeedPowerOff provides a mock function with given fields: logslevel
func (_m *IComputerUsecase) IsNeedPowerOff(logslevel uint8) {
	_m.Called(logslevel)
}

// SetPowerOff provides a mock function with given fields: pc
func (_m *IComputerUsecase) SetPowerOff(pc entity.MyPc) error {
	ret := _m.Called(pc)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.MyPc) error); ok {
		r0 = rf(pc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIComputerUsecase creates a new instance of IComputerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIComputerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IComputerUsecase {
	mock := &IComputerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
